# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 704)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_RX = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RX.setGeometry(QtCore.QRect(60, 100, 101, 24))
        self.pushButton_RX.setObjectName("pushButton_RX")
        self.pushButton_RF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RF.setGeometry(QtCore.QRect(60, 130, 101, 24))
        self.pushButton_RF.setObjectName("pushButton_RF")
        self.pushButton_DD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DD.setGeometry(QtCore.QRect(60, 160, 101, 24))
        self.pushButton_DD.setObjectName("pushButton_DD")
        self.pushButton_Quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Quit.setGeometry(QtCore.QRect(610, 550, 101, 24))
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.label_mode = QtWidgets.QLabel(self.centralwidget)
        self.label_mode.setGeometry(QtCore.QRect(10, 200, 201, 20))
        self.label_mode.setObjectName("label_mode")
        self.label_mode_label = QtWidgets.QLabel(self.centralwidget)
        self.label_mode_label.setGeometry(QtCore.QRect(10, 180, 41, 20))
        self.label_mode_label.setObjectName("label_mode_label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 851, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_Frequency_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_Frequency_plain_text.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.label_Frequency_plain_text.setObjectName("label_Frequency_plain_text")
        self.label_Frequency_response = QtWidgets.QLabel(self.groupBox)
        self.label_Frequency_response.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_Frequency_response.setObjectName("label_Frequency_response")
        self.label_sto_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_sto_plain_text.setGeometry(QtCore.QRect(120, 30, 121, 20))
        self.label_sto_plain_text.setObjectName("label_sto_plain_text")
        self.label_sto_response = QtWidgets.QLabel(self.groupBox)
        self.label_sto_response.setGeometry(QtCore.QRect(150, 50, 81, 21))
        self.label_sto_response.setObjectName("label_sto_response")
        self.label_au1_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_au1_plain_text.setGeometry(QtCore.QRect(260, 30, 71, 20))
        self.label_au1_plain_text.setObjectName("label_au1_plain_text")
        self.label_au1_response = QtWidgets.QLabel(self.groupBox)
        self.label_au1_response.setGeometry(QtCore.QRect(260, 50, 51, 41))
        self.label_au1_response.setObjectName("label_au1_response")
        self.label_md1_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_md1_plain_text.setGeometry(QtCore.QRect(350, 30, 111, 20))
        self.label_md1_plain_text.setObjectName("label_md1_plain_text")
        self.label_md1_response = QtWidgets.QLabel(self.groupBox)
        self.label_md1_response.setGeometry(QtCore.QRect(360, 50, 81, 21))
        self.label_md1_response.setObjectName("label_md1_response")
        self.label_AT_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_AT_plain_text.setGeometry(QtCore.QRect(510, 30, 81, 20))
        self.label_AT_plain_text.setObjectName("label_AT_plain_text")
        self.label_AT_response = QtWidgets.QLabel(self.groupBox)
        self.label_AT_response.setGeometry(QtCore.QRect(530, 50, 41, 21))
        self.label_AT_response.setObjectName("label_AT_response")
        self.label_TT_plain_text = QtWidgets.QLabel(self.groupBox)
        self.label_TT_plain_text.setGeometry(QtCore.QRect(590, 30, 111, 20))
        self.label_TT_plain_text.setObjectName("label_TT_plain_text")
        self.label_TT_response = QtWidgets.QLabel(self.groupBox)
        self.label_TT_response.setGeometry(QtCore.QRect(610, 50, 41, 21))
        self.label_TT_response.setObjectName("label_TT_response")
        self.pushButton_Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(510, 550, 101, 24))
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.pushButton_VA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VA.setGeometry(QtCore.QRect(60, 190, 101, 24))
        self.pushButton_VA.setObjectName("pushButton_VA")
        self.pushButton_VB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VB.setGeometry(QtCore.QRect(60, 220, 101, 24))
        self.pushButton_VB.setObjectName("pushButton_VB")
        self.textEdit_input_freq_VA = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_input_freq_VA.setGeometry(QtCore.QRect(180, 190, 104, 21))
        self.textEdit_input_freq_VA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_input_freq_VA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_input_freq_VA.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_input_freq_VA.setObjectName("textEdit_input_freq_VA")
        self.textEdit_input_freq_VB = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_input_freq_VB.setGeometry(QtCore.QRect(180, 220, 104, 21))
        self.textEdit_input_freq_VB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_input_freq_VB.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_input_freq_VB.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_input_freq_VB.setObjectName("textEdit_input_freq_VB")
        self.pushButton_SS = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SS.setGeometry(QtCore.QRect(60, 250, 101, 24))
        self.pushButton_SS.setObjectName("pushButton_SS")
        self.pushButton_ByHand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ByHand.setGeometry(QtCore.QRect(60, 280, 101, 24))
        self.pushButton_ByHand.setObjectName("pushButton_ByHand")
        self.textEdit_ByHand = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_ByHand.setGeometry(QtCore.QRect(180, 280, 104, 21))
        self.textEdit_ByHand.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_ByHand.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_ByHand.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_ByHand.setObjectName("textEdit_ByHand")
        self.pushButton_PA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PA.setGeometry(QtCore.QRect(60, 310, 101, 24))
        self.pushButton_PA.setObjectName("pushButton_PA")
        self.pushButton_PI = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PI.setGeometry(QtCore.QRect(60, 340, 101, 24))
        self.pushButton_PI.setObjectName("pushButton_PI")
        self.textEdit_PA = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_PA.setGeometry(QtCore.QRect(180, 310, 104, 21))
        self.textEdit_PA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_PA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_PA.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_PA.setObjectName("textEdit_PA")
        self.textEdit_PI = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_PI.setGeometry(QtCore.QRect(180, 340, 104, 21))
        self.textEdit_PI.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_PI.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_PI.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_PI.setObjectName("textEdit_PI")
        self.doubleSpinBox_RF = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_RF.setGeometry(QtCore.QRect(170, 130, 101, 21))
        self.doubleSpinBox_RF.setMouseTracking(True)
        self.doubleSpinBox_RF.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_RF.setWrapping(True)
        self.doubleSpinBox_RF.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_RF.setAccelerated(True)
        self.doubleSpinBox_RF.setDecimals(4)
        self.doubleSpinBox_RF.setMaximum(100000.0)
        self.doubleSpinBox_RF.setSingleStep(0.025)
        self.doubleSpinBox_RF.setObjectName("doubleSpinBox_RF")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(780, 90, 50, 64))
        self.dial.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.dial.setProperty("value", 99)
        self.dial.setObjectName("dial")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(710, 160, 160, 178))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_NFM = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_NFM.setObjectName("radioButton_NFM")
        self.verticalLayout_3.addWidget(self.radioButton_NFM)
        self.radioButton_WFM = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_WFM.setObjectName("radioButton_WFM")
        self.verticalLayout_3.addWidget(self.radioButton_WFM)
        self.radioButton_AM = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_AM.setObjectName("radioButton_AM")
        self.verticalLayout_3.addWidget(self.radioButton_AM)
        self.radioButton_USB = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_USB.setObjectName("radioButton_USB")
        self.verticalLayout_3.addWidget(self.radioButton_USB)
        self.radioButton_LSB = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_LSB.setObjectName("radioButton_LSB")
        self.verticalLayout_3.addWidget(self.radioButton_LSB)
        self.radioButton_CW = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_CW.setObjectName("radioButton_CW")
        self.verticalLayout_3.addWidget(self.radioButton_CW)
        self.radioButton_AU = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_AU.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.radioButton_AU.setObjectName("radioButton_AU")
        self.verticalLayout_3.addWidget(self.radioButton_AU)
        self.pushButton_LC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LC.setGeometry(QtCore.QRect(340, 310, 101, 24))
        self.pushButton_LC.setObjectName("pushButton_LC")
        self.pushButton_LM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LM.setGeometry(QtCore.QRect(340, 340, 101, 24))
        self.pushButton_LM.setObjectName("pushButton_LM")
        self.lineEdit_LC = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LC.setGeometry(QtCore.QRect(460, 310, 113, 23))
        self.lineEdit_LC.setObjectName("lineEdit_LC")
        self.progressBar_LC = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_LC.setGeometry(QtCore.QRect(460, 340, 118, 23))
        self.progressBar_LC.setMaximum(63)
        self.progressBar_LC.setProperty("value", 0)
        self.progressBar_LC.setObjectName("progressBar_LC")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(580, 160, 111, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Monitor = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Monitor.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Monitor.setObjectName("verticalLayout_Monitor")
        self.radioButton_mute_off = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_mute_off.setObjectName("radioButton_mute_off")
        self.verticalLayout_Monitor.addWidget(self.radioButton_mute_off)
        self.radioButton_mute_on = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_mute_on.setObjectName("radioButton_mute_on")
        self.verticalLayout_Monitor.addWidget(self.radioButton_mute_on)
        self.radioButton_mute_normal = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_mute_normal.setObjectName("radioButton_mute_normal")
        self.verticalLayout_Monitor.addWidget(self.radioButton_mute_normal)
        self.label_serialValues = QtWidgets.QLabel(self.centralwidget)
        self.label_serialValues.setGeometry(QtCore.QRect(1, 401, 841, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_serialValues.setPalette(palette)
        self.label_serialValues.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_serialValues.setFrameShape(QtWidgets.QFrame.Box)
        self.label_serialValues.setScaledContents(True)
        self.label_serialValues.setWordWrap(True)
        self.label_serialValues.setObjectName("label_serialValues")
        self.label_serialValues_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_serialValues_2.setGeometry(QtCore.QRect(0, 420, 841, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_serialValues_2.setPalette(palette)
        self.label_serialValues_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_serialValues_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_serialValues_2.setScaledContents(True)
        self.label_serialValues_2.setWordWrap(True)
        self.label_serialValues_2.setObjectName("label_serialValues_2")
        self.label_serialResponse = QtWidgets.QLabel(self.centralwidget)
        self.label_serialResponse.setGeometry(QtCore.QRect(0, 440, 841, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_serialResponse.setPalette(palette)
        self.label_serialResponse.setFrameShape(QtWidgets.QFrame.Box)
        self.label_serialResponse.setObjectName("label_serialResponse")
        self.label_initialise = QtWidgets.QLabel(self.centralwidget)
        self.label_initialise.setGeometry(QtCore.QRect(0, 460, 841, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_initialise.setPalette(palette)
        self.label_initialise.setFrameShape(QtWidgets.QFrame.Box)
        self.label_initialise.setObjectName("label_initialise")
        self.label_radio_response = QtWidgets.QLabel(self.centralwidget)
        self.label_radio_response.setGeometry(QtCore.QRect(0, 480, 841, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_radio_response.setPalette(palette)
        self.label_radio_response.setFrameShape(QtWidgets.QFrame.Box)
        self.label_radio_response.setObjectName("label_radio_response")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(0, 500, 221, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_error.setPalette(palette)
        self.label_error.setFrameShape(QtWidgets.QFrame.Box)
        self.label_error.setObjectName("label_error")
        self.label_ResponseBack = QtWidgets.QLabel(self.centralwidget)
        self.label_ResponseBack.setGeometry(QtCore.QRect(220, 500, 261, 21))
        self.label_ResponseBack.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ResponseBack.setObjectName("label_ResponseBack")
        self.tableWidget_Station = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Station.setGeometry(QtCore.QRect(310, 90, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Station.sizePolicy().hasHeightForWidth())
        self.tableWidget_Station.setSizePolicy(sizePolicy)
        self.tableWidget_Station.setRowCount(1)
        self.tableWidget_Station.setColumnCount(3)
        self.tableWidget_Station.setObjectName("tableWidget_Station")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(600, 120, 66, 23))
        self.doubleSpinBox.setSingleStep(0.025)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 90, 111, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_AutoStepMode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_AutoStepMode.setGeometry(QtCore.QRect(580, 250, 121, 20))
        self.checkBox_AutoStepMode.setChecked(True)
        self.checkBox_AutoStepMode.setObjectName("checkBox_AutoStepMode")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 19))
        self.menubar.setObjectName("menubar")
        self.menuWoy = QtWidgets.QMenu(self.menubar)
        self.menuWoy.setObjectName("menuWoy")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWoy.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_Quit.clicked.connect(MainWindow.close)
        self.radioButton_CW.clicked.connect(self.textEdit_PI.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ar8000 Controller"))
        self.pushButton_RX.setText(_translate("MainWindow", "RX"))
        self.pushButton_RF.setText(_translate("MainWindow", "RF"))
        self.pushButton_DD.setText(_translate("MainWindow", "DD"))
        self.pushButton_Quit.setText(_translate("MainWindow", "Quit"))
        self.label_mode.setText(_translate("MainWindow", "Mode"))
        self.label_mode_label.setText(_translate("MainWindow", "Mode"))
        self.groupBox.setTitle(_translate("MainWindow", "Status"))
        self.label_Frequency_plain_text.setText(_translate("MainWindow", "Frequency"))
        self.label_Frequency_response.setText(_translate("MainWindow", "Frequency"))
        self.label_sto_plain_text.setText(_translate("MainWindow", "Tuning Step Mode"))
        self.label_sto_response.setText(_translate("MainWindow", "sto"))
        self.label_au1_plain_text.setText(_translate("MainWindow", "Auto Mode"))
        self.label_au1_response.setText(_translate("MainWindow", "au"))
        self.label_md1_plain_text.setText(_translate("MainWindow", "Receiver Mode"))
        self.label_md1_response.setText(_translate("MainWindow", "md1"))
        self.label_AT_plain_text.setText(_translate("MainWindow", "Attenuator"))
        self.label_AT_response.setText(_translate("MainWindow", "AT"))
        self.label_TT_plain_text.setText(_translate("MainWindow", "Text Search Bank"))
        self.label_TT_response.setText(_translate("MainWindow", "TT"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_VA.setText(_translate("MainWindow", "VA"))
        self.pushButton_VB.setText(_translate("MainWindow", "VB"))
        self.pushButton_SS.setText(_translate("MainWindow", "SS"))
        self.pushButton_ByHand.setText(_translate("MainWindow", "By Hand"))
        self.pushButton_PA.setText(_translate("MainWindow", "PA"))
        self.pushButton_PI.setText(_translate("MainWindow", "PI"))
        self.radioButton_NFM.setText(_translate("MainWindow", "NFM"))
        self.radioButton_WFM.setText(_translate("MainWindow", "WFM"))
        self.radioButton_AM.setText(_translate("MainWindow", "AM"))
        self.radioButton_USB.setText(_translate("MainWindow", "USB"))
        self.radioButton_LSB.setText(_translate("MainWindow", "LSB"))
        self.radioButton_CW.setText(_translate("MainWindow", "CW"))
        self.radioButton_AU.setText(_translate("MainWindow", "AU"))
        self.pushButton_LC.setText(_translate("MainWindow", "LC"))
        self.pushButton_LM.setText(_translate("MainWindow", "LM"))
        self.radioButton_mute_off.setText(_translate("MainWindow", "Mute Off"))
        self.radioButton_mute_on.setText(_translate("MainWindow", "Mute On"))
        self.radioButton_mute_normal.setText(_translate("MainWindow", "Normal"))
        self.label_serialValues.setText(_translate("MainWindow", "serial values"))
        self.label_serialValues_2.setText(_translate("MainWindow", "serial values 2"))
        self.label_serialResponse.setText(_translate("MainWindow", "serial response"))
        self.label_initialise.setText(_translate("MainWindow", "initialise"))
        self.label_radio_response.setText(_translate("MainWindow", "Radio Response"))
        self.label_error.setText(_translate("MainWindow", "error"))
        self.label_ResponseBack.setText(_translate("MainWindow", "Response_back"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step Size"))
        self.checkBox_AutoStepMode.setText(_translate("MainWindow", "Auto Step Mode"))
        self.menuWoy.setTitle(_translate("MainWindow", "woy"))

